services:
  postgres:
    image: postgres:16
    container_name: bankcards-postgres
    environment:
      POSTGRES_DB: bankcards
      POSTGRES_USER: bank
      POSTGRES_PASSWORD: bank
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U bank -d bankcards" ]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bankcards-app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      JWT_SECRET: ${JWT_SECRET}
      CARD_ENCRYPTION_KEY: ${CARD_ENCRYPTION_KEY}
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  postgres_data:
